services:
  - type: web
    name: docbot
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn docbot.wsgi:application"
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.7
      - key: WEB_CONCURRENCY
        value: 2